image: docker:latest
services:
    - docker:dind

stages:
    - build
    
build:
  image: maven:3.8-openjdk-11
  stage: build
  script:
   - "cd ics-back-end && mvn clean install"
  artifacts:
    paths:
    - ics-back-end/target/*.jar
