create table images
(
    id          int4 generated by default as identity,
    height      int4,
    analysed_at varchar(255),
    url         varchar(255),
    width       int4,
    primary key (id)
);
create table images_tags
(
    tag_id   int4 not null,
    image_id int4 not null
);
create table tags
(
    id         int4 generated by default as identity,
    confidence int2,
    name       varchar(255),
    primary key (id)
);
alter table if exists images_tags
    add constraint FK21f4xbrqud8fwi845gh5n9b6n foreign key (image_id) references images;
alter table if exists images_tags
    add constraint FK6oqh5jec0q3ijtx1qqpmyf19v foreign key (tag_id) references tags;
